name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact to download.
        required: false
        default: dist
        type: string
    # secrets:
    # some-secret:
    # required: false
    outputs:
      step-result:
        description: The result of the deployment step.
        value: ${{jobs.deploy.outputs.outcome}}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
      - name: List downloaded files
        run: ls -la
      - name: Deploy
        run: echo "Deploying project..."
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
